[package]
name = "groceries_list"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.132"
wasm-bindgen = "0.2.95"
web-sys = { version = "0.3.61", features = ["Window", "Storage"] }

[lib]
crate-type = ["cdylib", "rlib"]
